#!/bin/bash

# Change Project Here:
PROJ=reminders

#
mkdir -p src/github.com/mchirico
mkdir -p bin

export GOPATH=`pwd`
export PATH="$(pwd)/bin:$PATH"
export GOBIN="$(pwd)/bin"
if ! [ -x "$(command -v godep)" ]; then
    echo 'Note: godep is not installed.' >&2
    echo '... we will install it ..' >&2    
    go get github.com/tools/godep
  
fi


if [ -d "$PWD/src/github.com/mchirico/$PROJ" ]; then
    cd "$PWD/src/github.com/mchirico/$PROJ"
else
    echo -e '

       cd src/github.com/mchirico
       git clone git@github.com:mchirico/${PROJ}.git

'
fi



